name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: azure/docker-build-push@v1
        with:
          azure-container-registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ github.repository }}:latest
          include-tags: latest
